on:
  push:
    paths:
      - 'frontend/**'
name: 🚀 Deploy frontend on push
jobs:
  client-deploy:
    name: 🎉 Deploy Frontend-Client
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 14
      uses: actions/setup-node@v2-beta
      with:
        node-version: '14'

    - name: 🔨 Build Project
      working-directory: ./frontend
      run: |
        npm install
        CI=false npm run build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: 194.62.40.12
        port: 21
        username: admin_hhg
        password: ${{ secrets.ftp_password }}
        local-dir: ./frontend/build/
        server-dir: public_html/clientcentral/
